### ISSUE TITLE
Error "Too many requests"

### ISSUE THREAD

**Issue by tradeverik** [joeyhage/homebridge-alexa-smarthome#110] opened 2024-02-07 19:47 UTC
**I always get the error: [7.2.2024, 20:36:31] [HomebridgeAlexaSmartHome] After initialization - RequestUnsuccessful(Error getting smart home device state(s). Response: {
  "message": "Too many requests. Try again in some time."
})
How can I solve this issue?

I added two devices by name and disabled auto refresh.**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

- **Plugin Version**:
- **Homebridge Version **: 
- **Node.js Version**: 
- **NPM Version**: 
- **Operating System**:

**Comment by joeyhage** [comment] 2024-02-07 23:16
Please see the official homebridge discord for the latest updates. This is being reported by many others: https://discord.gg/g98u9BfC

**Comment by billymcintosh** [comment] 2024-02-12 00:33
Do we really need to sign up for something else to find out what the issue is?

**Comment by joeyhage** [comment] 2024-02-12 03:24
The issue is on Amazon’s side. I made a small change in v2.1.3 to try to help and some people have reported improvements

**Comment by willryan042** [comment] 2024-05-01 16:07
Same issue here. Rolling back the plugin to v2.0.6 seems to have things working again at least for me.

**Comment by nfasolo** [comment] 2024-05-02 21:59
Thanks @willryan042. That's seems to have helped. We shall see if it holds.

**Comment by jpmorrison** [comment] 2024-05-03 03:29
Rolling back to 2.1.3 also helped. 2.1.4 was working then lost control of devices.

With 21.3 Echo Dot says it's muted. I never saw that in 2.1.4, so I don't know if that's good/bad.

**Comment by realugbun** [comment] 2024-06-06 02:52
Rolling back to 2.1.3 did not work for me. Rolling back to 2.0.6 got mine working again.

**Comment by realugbun** [comment] 2024-06-07 02:45
Update v2.1.2 is also working for me.

**Comment by jpmorrison** [comment] 2024-06-07 05:22
2.1.3 stopped working for me. I downgraded to 2.0.8 and it’s working again

**Comment by nfasolo** [comment] 2024-06-13 01:08
None of them are working for me now. Not sure what to do. This sucks.

**Comment by willryan042** [comment] 2024-06-13 15:40
Yep, unfortunately I've started getting the error again on 2.0.6 as well.

**Comment by jpmorrison** [comment] 2024-06-13 16:38
Same here. Is there a workaround/fix? The discord link is expired

**Comment by tddrmrz** [comment] 2024-06-15 16:40
@joeyhage Looks like you're trying to correct with some updates, but nothing mentioned in this thread is working for me thus far.

As other have mentioned, I also cannot access the discord link you posted for updates/etc.  Is that still alive?  If not, can you help break things down for us as to what's going on?  Is Amazon pulling the same stunt as MyQ did not long ago and shut this kind of solution out?

Hoping a solution is in the works now that I've spent enough on powered shades to have bought a new car.  Would certaibnly be nice to not have to suffer through Tahoma's/Somfy's crappy app.

**Comment by joeyhage** [comment] 2024-06-27 00:49
See #137 for the latest thread and all updates. Closing this issue in favor of #137.

**Closed** 2024-06-27 00:49 UTC
Labels: question
